---
title: "table_one"
author: "Jochen Kruppa"
date: "19 April 2021"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tableone, table1, survival, tidyverse)
## tableone package itself
data(pbc)
```

## Data

```{r data}

pbc_tbl <- as_tibble(pbc)

```

## Table one

The percentages are calculated after excluding missing values

```{r table one}

## dput(names(pbc))

myVars <- c("time", "status", "trt", "age", "sex", "ascites", "hepato",
          "spiders", "edema", "bili", "chol", "albumin", "copper", "alk.phos",
          "ast", "trig", "platelet", "protime", "stage")

catVars <- c("status", "trt", "ascites", "hepato",
             "spiders", "edema", "stage")


table_one <- CreateTableOne(vars = myVars, data = pbc, factorVars = catVars)

## print(table_one, showAllLevels = TRUE)

summary(table_one)

biomarkers <- c("bili","chol","copper","alk.phos","ast","trig","protime")

print(table_one, nonnormal = biomarkers, formatOptions = list(big.mark = ",")) %>%
  kableone()

## kableone(tableOne)

```

## Problems

Variable edema has 0, 0.5 and 1. Is this okay?

## Stratifiziert nach einer beliebigen Variable

```{r strata}

tab3 <- CreateTableOne(vars = myVars, 
                       strata = "trt" , ## stratifiziert nach trt
                       data = pbc_tbl, 
                       factorVars = catVars)

print(tab3, nonnormal = biomarkers, 
      formatOptions = list(big.mark = ",")) %>%
  kableone()




```

## Und nochmal zum Ausrasten

https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Overview


```{r table1}

library(boot) 

melanoma2 <- melanoma
 
# Factor the basic variables that
# we're interested in
melanoma2$status <- 
  factor(melanoma2$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))

table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)

```


